pipeline:
  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    repo: quay.io/aliyanaziz/cicd
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  build_tag:
    image: ukhomeoffice/drone-docker
    repo: quay.io/aliyanaziz/cicd
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

  deploy-to-kube:
    image: ukhomeoffice/drone-docker
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=quay.io/aliyanaziz/cicd:${DRONE_TAG}
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh
    when:
      event: deployment