pipeline:
  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: quay.io/hodacc/cicdws
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  build_tag:
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: quay.io/hodacc/cicdws
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag


  deploy-to-kube:
    image: quay.io/ukhomeofficedigital/kd:v1.10.6
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=quay.io/hodacc/cicdws:v0.1
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh
    when:
      event: deployment
